import { PostCardType } from "@/types/board-type";

export const boardData: PostCardType[] = [
  {
    id: "1",
    site: "dcinside",
    title: "DC 갤러리ㅈㄹㄷㄹㅈㅈㄷㅈㄹㄷㄹㅈㄷ 게시글 1",
    url: "https://dcinside.com/post1",
    createTime: new Date("2024-03-01T08:00:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 1.",
  },
  {
    id: "2",
    site: "dcinside",
    title: "DC 갤러리 게시글 2",
    url: "https://dcinside.com/post2",
    createTime: new Date("2024-02-29T15:30:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 2.",
  },
  {
    id: "3",
    site: "dcinside",
    title: "DC 갤러리 게시글 3",
    url: "https://dcinside.com/post3",
    createTime: new Date("2024-02-28T12:45:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 3.",
  },
  {
    id: "4",
    site: "ygosu",
    title: "와이고수 포스트 1",
    url: "https://ygosu.com/post1",
    createTime: new Date("2024-03-01T10:00:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 4.",
  },
  {
    id: "5",
    site: "ygosu",
    title: "와이고수 포스트 2",
    url: "https://ygosu.com/post2",
    createTime: new Date("2024-02-29T16:30:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 5.",
  },
  {
    id: "6",
    site: "ygosu",
    title: "와이고수 포스트 3",
    url: "https://ygosu.com/post3",
    createTime: new Date("2024-02-28T13:45:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 6.",
  },
  {
    id: "7",
    site: "ppomppu",
    title: "뽐뿌 게시물 1",
    url: "https://ppomppu.co.kr/post1",
    createTime: new Date("2024-03-01T11:00:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 7.",
  },
  {
    id: "8",
    site: "ppomppu",
    title: "뽐뿌 게시물 2",
    url: "https://ppomppu.co.kr/post2",
    createTime: new Date("2024-02-29T17:30:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 8.",
  },
  {
    id: "9",
    site: "ppomppu",
    title: "뽐뿌 게시물 3",
    url: "https://ppomppu.co.kr/post3",
    createTime: new Date("2024-02-28T14:45:00Z"),
    GPTAnswer: "This is a sample GPT answer for post 9.",
  },
];
