name: Next.js CI/CD

on:
  push:
    branches: [feature/KIN-26-Front-git-action-script]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Build Docker image
      run: |
        docker build -t kingwangjjang-client:0.0.1 .
        docker tag kingwangjjang-client:0.0.1 ${{ secrets.DOCKERHUB_USERNAME }}/kingwangjjang-client:0.0.1

    - name: Push Docker image to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/kingwangjjang-client:0.0.1

  run:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
        
    steps:
    # WAS 인스턴스 접속 & 애플리케이션 실행
    - name: Connect to WAS & Execute Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WAS_HOST }}
        username: ${{ secrets.WAS_USERNAME }}
        key: ${{secrets.SSH_KEY}}
        port: ${{ secrets.WAS_SSH_PORT }}
        script: |
          sudo -S /usr/local/bin/docker version <<< "${{ secrets.WAS_PASSWORD }}"
          sudo -S /usr/local/bin/docker rm -f kingwangjjang-client || true
          sudo -S /usr/local/bin/docker pull ${{ secrets.DOCKERHUB_USERNAME }}/kingwangjjang-client:0.0.1 <<< "${{ secrets.WAS_PASSWORD }}"
          sudo -S /usr/local/bin/docker run -d --name kingwangjjang-client:0.0.1 <<< "${{ secrets.WAS_PASSWORD }}"
      